//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod system_dept;
pub mod system_dict_data;
pub mod system_dict_type;
pub mod system_login_log;
pub mod system_mail_account;
pub mod system_mail_log;
pub mod system_mail_template;
pub mod system_menu;
pub mod system_notice;
pub mod system_notify_message;
pub mod system_notify_template;
pub mod system_oauth2_access_token;
pub mod system_oauth2_approve;
pub mod system_oauth2_client;
pub mod system_oauth2_code;
pub mod system_oauth2_refresh_token;
pub mod system_operate_log;
pub mod system_post;
pub mod system_role;
pub mod system_role_menu;
pub mod system_sms_channel;
pub mod system_sms_code;
pub mod system_sms_log;
pub mod system_sms_template;
pub mod system_social_client;
pub mod system_social_user;
pub mod system_social_user_bind;
pub mod system_tenant;
pub mod system_tenant_package;
pub mod system_user_post;
pub mod system_user_role;
pub mod system_users;
